import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./nav";
import Footer from "./footer";
import StarBackground from './StarBackground'
import VideoBackground from "./videobakground";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#000000] overflow-y-scroll overflow-x-hidden`}>
        <StarBackground/>
        <Nav />        
        {children}
        <Footer />
      </body>
    </html>
  );
}
